### ISSUE TITLE
Suggestion for collab

### ISSUE THREAD

**Issue by guyluz11** [babincc/flutter_workshop#11]
Different packages doing the same thing is sometimes the right choice.
Even better option is to support about native and not just flutter, this way server side can use your code as well and maybe even the web.

I have found this package (I am not the author)
https://pub.dev/packages/hue_dart

And decided to suggest here to turn your package in too dart native all collaborate with the other package which is already supported alternative.

**Comment by babincc** [comment]
Thank you for your idea. When I was thinking of creating Flutter Hue, I checked pub.dev to see if anyone had already done it. I saw this package that you are suggesting, and I looked into it. This package is using v1 of the Philips Hue API. My package is using Philips Hue's v2 API. My package and the one you are suggesting, do essentially the same thing. They just use different versions of the Hue API.

If this response is satisfactory, you can go ahead and close this issue; otherwise, feel free to ask questions or share more info. Thanks!

**Comment by guyluz11** [comment]
Interesting.

Can you turn this package into dart native?.

No flutter dependencies so that it could run on dart several side as well.

**Comment by babincc** [comment]
I'm sure it can be done, but this package was designed to be added to applications that users would interact with directly. It was not made to be a server application.

The other package you suggested also appears to be the same way. It is dependent on Flutter as well.

**Comment by guyluz11** [comment]
The other package already support Dart native.
I'm using it and you can spot it by this icon

![Screenshot_20240110_211253_Firefox](https://github.com/babincc/flutter_workshop/assets/9304740/d470f24d-6961-4ef3-9fac-4f344386e321)

**Comment by babincc** [comment]
Oh, I see what you mean. My mistake. 

The first part of my response is still true though. My package was designed to be used directly in user apps. If I were to convert it to be able to be a server app, it would require a large redesign.

**Comment by babincc** [comment]
I believe I have addressed all of your concerns; so, I am going to go ahead and close this issue. If you have any more questions, feel free to re-open it, or open a new one. Thanks!
